config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :categories
  resources :products 
  root 'users#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	mount_uploader :image, ImageProductUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_search

	def set_search
	@search=Product.search(params[:q])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 def new
      @category= Category.new  
  end

  def create
  		@category = Category.new(user_params)
  		if @category.save
        flash[:success] = "Add Category sucessful!"
  			redirect_to new_category_path
  		else
  			render 'new'
  		end
  end

  def index

  end

  def show
    @category = Category.find(params[:id])
    @categorys = Category.all
    @product = Product.where(categori_id: @category)
   @products = Product.paginate(:page => params[:page], :per_page =>8)

  end

  def user_params
      params.require(:category).permit(:name)
  end

  def destroy
      
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

 def new
  	  @product = Product.new
      @category= Category.all
  end

  def create
  		@product = Product.new(user_params)
  		if @product.save
  			redirect_to root_path
  		else
  			render 'new'
  		end
  end
    def show
        @categorys = Category.all
        @product =Product.find(params[:id])
        @categori = Category.find(@product.categori_id)
    end

      def index
          @categorys = Category.all
          @search = Product.ransack(params[:q])
          @products = @search.result(distinct: true)
          respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @products }
          end
          @product = @products.paginate(:page => params[:page], :per_page => 8 )
      end

  def user_params
      params.require(:product).permit(:product_name, :price, :image,
                                   :description, :categori_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def new
      get_pre_login_url
      super
    end
    def create
      @referer_url = root_path
      super
    end
    def destroy
      @referer_url = root_path
      super
    end
    private
    def get_pre_login_url
      @referer_url = root_path
    end
    def after_sign_in_path_for resource
      sign_in_url = url_for(action: "new", controller: "sessions", only_path: false, protocol: "http")
      if @referer_url == sign_in_url
      super
    else
      @referer_url || root_path
    end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_search  
  
  def home
    @category = Category.all
    @products = Product.last(8)
    @product = Product.paginate(:page => params[:page], :per_page =>8)
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
    @category =  Category.find(params[:id])
    flash[:success] = "Category deleted"
    @category.destroy
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

def set_search
   @search = Product.ransack(params[:q])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<% if user_signed_in?%>
 <h1> Add Category </h1>
 <%= form_for @category do |f| %>
 <%= f.label :Category %>
 <%= f.text_field :name %>
 <%= f.submit "Add Category" ,class: "btn btn-primary" %>
 <% end %>
 <% end %>

app/views/categories/show.html.erb
<p><%= link_to 'Home > ',root_path %><%= link_to @category.name , category_path(@category.id) %></p><br >
<div class = "col-sm-2">
<p class = "category"> Category </p>
<div>
	<% @categorys.each do |category| %>
	<p> <%=link_to category.name ,category_path(category.id) %></p>
	<% end %>
</div>
</div>

<div class = "col-sm-10">
<p class = "title_items" > <%=@category.name %></p>
	<% @product.each do |product| %>
	<div class="img">
	<img src = '<%= product.image %>' alt=product.img>
	<br ><span class='blue'><%=product.product_name %></span><br >
	<p><span class='red'> Price: <%= product.price %> VND</span><br ></p>
	</div>
	<% end %>
</div>
<div class="col-sm-12"><%= will_paginate @products%></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "VenShop", root_path ,id: "logo" %>
     <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '' %></li>
        <% if user_signed_in?  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
               <li><%= link_to "Settings", edit_user_registration_path %></li>
               <li><%= link_to "Add Product", new_product_path %></li>
               <% if current_user.admin? %>
               <li><%= link_to "Add Category", new_category_path %></li>
               <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
   <%= search_form_for @search ,class: "form-inline" do |f| %>
   <%= f.search_field :product_name_or_price_start,class: "form-control"%>
   <span class="left">
   <%= f.submit "Search" ,class: "btn btn-primary"%>
   </span>
    <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VenShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/header' %>
</head>
<body>
      <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <br ><br >
      <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/index.html.erb
<p><%= link_to 'Home > ',root_path %><%= link_to "Search Result" ,'' %></p>
<div class = "col-sm-2">
<p class = "category"> Category </p>
<div>
	<% @categorys.each do |category| %>
	<p> <%=link_to category.name ,category_path(category.id) %></p>
	<% end %>
</div>
</div>

<div class = "col-sm-10">
<p class = "title_items" >Result for <%=@search.product_name_or_price_start %></p>
	<% @products.each do |product| %>
	<div class="img">
	
	<%= link_to product_path(product.id) do%>
		<img src = '<%=product.image %>' alt= product.img>
	<% end%>
	<br ><span class='blue'><%=product.product_name %></span><br >
	<p><span class='red'> Price: <%= product.price %> VND</span><br ></p>
	</div>
	<% end %>

</div>

app/views/products/new.html.erb
 <% if user_signed_in? %>
 <h1> Add Product </h1>
 <%= form_for(@product, html: { multipart: true }) do |f| %>
 <%= pluralize(@product.errors.count, "error") %>.
 <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %><br >
 <%= f.label :Category %>
 <%= f.select(:categori_id, Category.all.collect {|p| [ p.name, p.id ] })%> <br >
 <%= f.label :Name_Product %>
 <%= f.text_field :product_name,  class: 'form-control' %>

 <%= f.label :Price %>
 <%= f.text_field :price , class: 'form-control'%>

 <%= f.label :Image %>
 <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>

 <%= f.label :Description %>
 <%= f.text_field :description , class: 'form-control'%>

 <%= f.submit "Add Product" ,class: "btn btn-primary" %>
 <% end %>
 <% end %>

app/views/products/show.html.erb
<p><%= link_to 'Home > ',root_path %><%= link_to @categori.name+'> ' ,category_path%><%=link_to @product.product_name+'','' %>
<div class = "col-sm-2">
<p class = "category"> Category </p>
<div>
	<% @categorys.each do |category| %>
	<p> <%=link_to category.name ,category_path(category.id) %></p>
	<% end %>
</div>
</div>

<div class = "col-sm-10">
<p class = "title_items" > <%=@product.product_name%></p>
<div class="col-sm-4">
	<div class="item">
	<img src = '<%= @product.image %>' alt=product.img>
	<br ><span class='blue'><%=@product.product_name %> ID <%=@product.id %></span><br >
	<p><span class='red'> Price: <%= @product.price %> VND</span><br ></p>
	<span class='blue'><%=@product.created_at %></span><br >
	</div>
</div>
	<div class="col-sm-6">
	<%=form_for(@product) do |f| %>
	<%= f.text_area :description ,:id => "message_area" ,:readonly => true%>
	<%= f.submit "Mua" ,class: "btn btn-primary",:id => "submit" %>
	<% end %>
	</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/home.html.erb
<p class='left'><%= link_to 'Home',root_path %></p>
<div class = "col-sm-2">
<p class = "category"> Category </p>
<div>
	<% @category.each do |category| %>
	<p> <%=link_to category.name ,category_path(category.id) %>
	<% if user_signed_in? && current_user.admin? %> 
	 <%= link_to "delete", user_path(category.id), class: "delete", method: :delete,
                                       data: { confirm: "You sure?" } %><% end %></p>
	<% end %>
</div>
</div>

<div class = "col-sm-10">
<p class = "title_items" > Items </p>
	<% @product.each do |product| %>
	<div class="img">

	<%= link_to product_path(product.id) do%>
		<img src = '<%=product.image %>' alt= product.img>
	<% end%>

	<br ><span class ='blue'><%=product.product_name %></span><br >
	<p> <span class ='red'>Price: <%= product.price %> VND</span><br></p>
	<!-- <span class='border'><%= link_to 'Mua' ,'#', data: {confirm: "Are you sure ?"}%></span><br > -->
	</div>
	<% end %>
</div>
<div class="col-sm-12"><%= will_paginate @product%></div>

<div class = "col-sm-2">
</div>

<div class = "col-sm-10">
<p class = "newest" > Newest </p>
	<% @products.each do |product| %>
	<div class="img">
		<%= link_to product_path(product.id) do%>
		<img src = '<%=product.image %>' alt= product.img>
	<% end%>
	<br ><span class ='blue'><%=product.product_name %></span><br >
	<p><span class='red'> Price: <%= product.price %> VND</span><br ></p>
	</div>
	<% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<%= @user.email %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>